### ISSUE TITLE
Question about Eq. 16

### ISSUE THREAD

**Issue by toyot-li** [2y7c3/ASD#2]
Hi @2y7c3, thanks for your awesome work. As for the last two terms in the last line of Eqn. 16, I am confused about how to convert the penalty term to the sum of these two l2 norms. Could you please provide a more detailed derivation? Thanks.

**Comment by 2y7c3** [comment]
According to [1], $\tilde{x}$ comes from a mixture distribution $\tilde{\mu}$, so it can be replaced by a combination of  
${x_t^r}$ and ${x_t^g}$. And we directly derive the gradient for penalty term, which is equal to the output of the diffusion model, i.e. $\nabla_{x_t} \log p(x_t|y)=-1/{\sigma_t} *{\epsilon_{x_t;y,t}}$


[1] Jiqing Wu, Zhiwu Huang, Janine Thoma, Dinesh Acharya, and Luc Van Gool. Wasserstein divergence for gans. In Proceedings of the European Conference on Computer Vision (ECCV), September 2018

**Comment by toyot-li** [comment]
@2y7c3 Hi, thanks. I know that based on the relation between noise prediction and score function, the equation becomes
$\tau \Vert \nabla_{\hat{x}_t} \log p(\hat{x}_t|y) - \nabla_{\hat{x}_t} \log p(\hat{x}_t|\phi) \Vert^2 = \tau (-1/{\sigma_t} *{\epsilon_{\hat{x}_t;y,t}} + 1/{\sigma_t} *{\epsilon_{\hat{x}_t;\phi,t}})$, but I am confused about how it can be converted to the last row of equation 16

**Comment by 2y7c3** [comment]
Please refer to supp section B in [1], study the effects of different sampling strategies corresponding to six types of $\tilde{\mu}$. We use the sampling strategy (4) (sampling both real or fake data points). Then samples $\tilde{x}$ can be replaced by a combination of $x_t^r$ and $x_t^g$. The penalty term can be split into two terms for real and fake samples. Finally, using the relation between noise prediction and score function to derive the last row in Eq.16.

[1] Jiqing Wu, Zhiwu Huang, Janine Thoma, Dinesh Acharya, and Luc Van Gool. Wasserstein divergence for gans. In Proceedings of the European Conference on Computer Vision (ECCV), September 2018

**Comment by toyot-li** [comment]
> The penalty term can be split into two terms for real and fake samples. Finally, using the relation between noise prediction and score function to derive the last row in Eq.16.

Could you please provide a mathematical derivation? I think it still stays at a conceptual level, instead of a strict proof, right?
